version: "3"

services:
  backend:
    build: ./src
    restart: always
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
